### ISSUE TITLE
ImportError: cannot import name 'moving_averages'

### ISSUE THREAD

**Issue by TJUXJH** [ewrfcas/QANet_keras#9]
hello,when I run  python train_QANet.py on colab,  error:

from keras.backend import moving_average
ImportError: cannot import name 'moving_averages'

**Comment by zhihongcheng** [comment]
I think you should pay attention to your keras version

**Comment by zhihongcheng** [comment]
when you solved this question，could you tell me your result of running this model？thanks

**Comment by TJUXJH** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hello,
        I am so sorry that I still don't solve the problem. I run the code  on google colab. I try to change the version of tensorflow. but the code doesn't work with tensoflow==1.6.0.I will appreciate it if you can share the information about the version of tensorflow and keras with me.Thank you
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                3015204145
                            
                            
                                
                            
                    
                        
                            
                                    3015204145@tju.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 12/3/2019 13:23，zhihongcheng<notifications@github.com> wrote： 


when you solved this question，could you tell me your result of running this model？thanks



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zhihongcheng** [comment]
The version i used keras is 2. 1. 4 and tensorflow version is 1. 7. 0------------------ 原始邮件 ------------------
发件人: "TJUXJH"<notifications@github.com>
发送时间: 2019年12月3日(星期二) 中午1:27
收件人: "ewrfcas/QANet_keras"<QANet_keras@noreply.github.com>;
抄送: "zhihongcheng"<747074886@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ewrfcas/QANet_keras] ImportError: cannot import name'moving_averages' (#9)


 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     Hello,
         I am so sorry that I still don't solve the problem. I run the code &#xA0;on google colab. I try to change the version of tensorflow. but the code doesn't work with tensoflow==1.6.0.I will appreciate it if you can share the information about the version of tensorflow and keras with me.Thank you
     
         
             
         
     
     
      
     
         
                     
             
                 
                     
                             
                                 
                             
                             
                                 3015204145
                             
                             
                                 
                             
                     
                         
                             
                                     3015204145@tju.edu.cn
                             
                         
                 
             
         
         
     
     
         签名由
         网易邮箱大师
         定制
     
  
 
     On 12/3/2019 13:23，zhihongcheng<notifications@github.com> wrote： 
 
 
 when you solved this question，could you tell me your result of running this model？thanks
 
 
 
 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zhihongcheng** [comment]
when you solved this question，could you tell me your result of running this model？thanks

**Comment by TJUXJH** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hello,I run the code againwhen it start to train, out of RAM(12G)
        
            
        
    
    
        this code can work well, get F1 score around 75 after 3 epoch! https://github.com/BangLiu/QANet-PyTorch
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                3015204145
                            
                            
                                
                            
                    
                        
                            
                                    3015204145@tju.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 12/3/2019 13:31，zhihongcheng<notifications@github.com> wrote： 


The version i used keras is 2. 1. 4 and tensorflow version is 1. 7. 0------------------ 原始邮件 ------------------



发件人: "TJUXJH"<notifications@github.com>



发送时间: 2019年12月3日(星期二) 中午1:27



收件人: "ewrfcas/QANet_keras"<QANet_keras@noreply.github.com>;



抄送: "zhihongcheng"<747074886@qq.com>;"Comment"<comment@noreply.github.com>;



主题: Re: [ewrfcas/QANet_keras] ImportError: cannot import name'moving_averages' (#9)











 



 



      



 



 



 



     font{ 



         line-height: 1.6; 



     } 



     ul,ol{ 



         padding-left: 20px; 



         list-style-position: inside; 



     } 



 



 



     



     Hello,



         I am so sorry that I still don't solve the problem. I run the code &#xA0;on google colab. I try to change the version of tensorflow. but the code doesn't work with tensoflow==1.6.0.I will appreciate it if you can share the information about the version of tensorflow and keras with me.Thank you



     



         



             



         



     



     



      



     



         



                     



             



                 



                     



                             



                                 



                             



                             



                                 3015204145



                             



                             



                                 



                             



                     



                         



                             



                                     3015204145@tju.edu.cn



                             



                         



                 



             



         



         



     



     



         签名由



         网易邮箱大师



         定制



     



  



 



     On 12/3/2019 13:23，zhihongcheng<notifications@github.com> wrote： 



 



 



 when you solved this question，could you tell me your result of running this model？thanks



 



 



 



 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 



&mdash;



You are receiving this because you commented.



Reply to this email directly, view it on GitHub, or unsubscribe.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zhihongcheng** [comment]
Thanks. OOMs happens to me，and it seems decrease the batch size can help it. ------------------ 原始邮件 ------------------
发件人: "TJUXJH"<notifications@github.com>
发送时间: 2019年12月3日(星期二) 晚上7:16
收件人: "ewrfcas/QANet_keras"<QANet_keras@noreply.github.com>;
抄送: "zhihongcheng"<747074886@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ewrfcas/QANet_keras] ImportError: cannot import name'moving_averages' (#9)


 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     Hello,I run the code againwhen it start to train, out of RAM(12G)
         
             
         
     
     
         this code can work well, get F1 score around 75 after 3 epoch!&#xA0;https://github.com/BangLiu/QANet-PyTorch
             
         
     
     
      
     
         
                     
             
                 
                     
                             
                                 
                             
                             
                                 3015204145
                             
                             
                                 
                             
                     
                         
                             
                                     3015204145@tju.edu.cn
                             
                         
                 
             
         
         
     
     
         签名由
         网易邮箱大师
         定制
     
  
 
     On 12/3/2019 13:31，zhihongcheng<notifications@github.com> wrote： 
 
 
 The version i used keras is 2. 1. 4 and tensorflow version is 1. 7. 0------------------ 原始邮&#x4EF6; ------------------
 
 
 
 发&#x4EF6;人: "TJUXJH"<notifications@github.com>
 
 
 
 发送时间: 2019年12月3日(星期&#x4E8C;) 中午1:27
 
 
 
 收&#x4EF6;人: "ewrfcas/QANet_keras"<QANet_keras@noreply.github.com>;
 
 
 
 抄送: "zhihongcheng"<747074886@qq.com>;"Comment"<comment@noreply.github.com>;
 
 
 
 主题: Re: [ewrfcas/QANet_keras] ImportError: cannot import name'moving_averages' (#9)
 
 
 
 
 
 
 
 
 
 
 
  
 
 
 
  
 
 
 
       
 
 
 
  
 
 
 
  
 
 
 
  
 
 
 
      font{ 
 
 
 
          line-height: 1.6; 
 
 
 
      } 
 
 
 
      ul,ol{ 
 
 
 
          padding-left: 20px; 
 
 
 
          list-style-position: inside; 
 
 
 
      } 
 
 
 
  
 
 
 
  
 
 
 
      
 
 
 
      Hello,
 
 
 
          I am so sorry that I still don't solve the problem. I run the code &#xA0;on google colab. I try to change the version of tensorflow. but the code doesn't work with tensoflow==1.6.0.I will appreciate it if you can share the information about the version of tensorflow and keras with me.Thank you
 
 
 
      
 
 
 
          
 
 
 
              
 
 
 
          
 
 
 
      
 
 
 
      
 
 
 
       
 
 
 
      
 
 
 
          
 
 
 
                      
 
 
 
              
 
 
 
                  
 
 
 
                      
 
 
 
                              
 
 
 
                                  
 
 
 
                              
 
 
 
                              
 
 
 
                                  3015204145
 
 
 
                              
 
 
 
                              
 
 
 
                                  
 
 
 
                              
 
 
 
                      
 
 
 
                          
 
 
 
                              
 
 
 
                                      3015204145@tju.edu.cn
 
 
 
                              
 
 
 
                          
 
 
 
                  
 
 
 
              
 
 
 
          
 
 
 
          
 
 
 
      
 
 
 
      
 
 
 
          签名由
 
 
 
          网易邮箱大师
 
 
 
          定制
 
 
 
      
 
 
 
   
 
 
 
  
 
 
 
      On 12/3/2019 13:23，zhihongcheng<notifications@github.com> wrote： 
 
 
 
  
 
 
 
  
 
 
 
  when you solved this question，could you tell me your result of running this model？thanks
 
 
 
  
 
 
 
  
 
 
 
  
 
 
 
  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 
 
 &mdash;
 
 
 
 You are receiving this because you commented.
 
 
 
 Reply to this email directly, view it on GitHub, or unsubscribe.
 
 
 
 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
